title: CuBlog
description: A tidy Jekyll Blog
baseurl: "CuBlog"
url: "https://ryanincn11.me"

# Style Settings
color_scheme: auto # auto/light/dark
accent_color: "#4a86e8"

# Social Accounts Settings
social:
  github: yourusername
  twitter: yourhandle
  linkedin: yourprofile
  email: your@email.com
  instagram: yourinsta
