title: 我的博客
description: 一个简洁的Jekyll博客
baseurl: ""
url: "https://yourusername.github.io"

# 主题配置
theme: auto # auto/light/dark
accent_color: "#4a86e8"

# 社交账户配置 (示例)
social:
  github: yourusername
  twitter: yourhandle
  linkedin: yourprofile
  email: your@email.com
  instagram: yourinsta