title: CuBlog
description: A tidy Jekyll Blog
baseurl: "CuBlog"
url: "https://ryanincn11.me"

# Style Settings
accent_color: "#4a86e8"

# Collections
collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:title/

# Pagination
paginate: 5
paginate_path: /blog/page:num

# Site Metadata
author: "Your Name"
email: "your@email.here"
timezone: "Europe/London"

# Internationalization
lang: en-GB

# Feed Configuration
plugins:
  - jekyll-feed

# Social Accounts
github_username: yourusername
facebook_username: yourusername
x_username: yourusername

# Build settings
markdown: kramdown
highlighter: rouge
