name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1
        
    - name: Install dependencies
      run: |
        gem install bundler
        bundle install
        
    - name: Build site
      run: bundle exec jekyll build --baseurl "${{ github.event.repository.name }}"
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: ./_site

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v2
